trigger:
 branches:
   include:
     - main

pr:
 branches:
   include:
     - main

variables:
  nodeVersion: '20.19.5'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test Stage'
    jobs:
      - job: BuildAndTestJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '$(nodeVersion)'
            displayName: 'Install NodeJS'

          - script: |
              npm install
            displayName: 'Install Dependencies'

          - script: |
              npm run build

          - task: ArchiveFiles@2
            inputs:
             rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
             includeRootFolder: false
             archiveType: 'zip'
             archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
             replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
              ArtifactName: 'drop'
              publishLocation: 'Container'